### PR TITLE
chore: use poetry for python dependencies

### PR DESCRIPTION
**Pull request by plexoos**

### CODE REVIEW

**Comment by rahmans1** [comment]
Just curious, is it not possible to handle this through spack alone?

**Comment by plexoos** [comment]
Yes, Spack can be used to install python packages. Looks like they have it https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-pyvista/package.py but I think there always be a lag between what Spack has and the releases in pypi https://pypi.org/project/pyvista/

**Comment by rahmans1** [comment]
> Yes, Spack can be used to install python packages. Looks like they have it https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-pyvista/package.py but I think there always be a lag between what Spack has and the releases in pypi https://pypi.org/project/pyvista/

We can request a version update or I can add myself as a maintainer for that spack package. It usually requires a small update like https://github.com/spack/spack/pull/41246 to have the version update if we require the most latest version.

**Comment by plexoos** [comment]
We can certainly consider Spack as package manager for python... But I think for now a more pressing issue that pyvista does not work with our GPU. Here I created an issue #76 Could you please take a look?

**Comment by buddhasystem** [comment]
@plexoos so installing "poetry" and its paraphernalia is just another attempt to display pyvista on your Mac?

**Comment by plexoos** [comment]
No

**Comment by plexoos** [comment]
It's for non-Mac user like you

**Comment by rahmans1** [comment]
I think the major python packages are available through spack. I am tempted to branch of beta and see how well that works instead of adding poetry as a separate dependency management tool. 

https://packages.spack.io/package.html?name=py-ipython
https://packages.spack.io/package.html?name=py-numpy

**Comment by plexoos** [comment]
> I started with './esi-shell -v PR-72'. Is there something else that I am missing?

Please download the updated `esi-shell` script from the branch corresponding to this PR, like so:

```
curl -Os https://raw.githubusercontent.com/BNLNPPS/esi-shell/pr/poetry/esi-shell && chmod u+x esi-shell
```

**Comment by rahmans1** [comment]
> > I started with './esi-shell -v PR-72'. Is there something else that I am missing?
> 
> Please download the updated `esi-shell` script from the branch corresponding to this PR, like so:
> 

I get the same error after getting the updated esi-shell script

**Comment by plexoos** [comment]
You reported two errors. The updated `esi-shell` addressed the first one where it could not find a pyproject.toml. Now, you don't need to install with poetry by hand.

The second one  about "This system does not appear to be running an xserver ... " is because you are running remotely and X windows cannot be opened locally. If you have a direct access to a GPU machine (NVidia of course) with X11, this error should not appear. Unfortunately, I don't have such machine to test but that is what I expect.

Maxim @buddhasystem it seems like you have a local NVidia GPU. Could you try the test I suggested above to see if we get any visuals from it?

**Pull request merged**
